package jdr.exia.update

import io.ktor.client.*
import io.ktor.client.call.*
import io.ktor.client.features.*
import io.ktor.client.features.json.*
import io.ktor.client.features.json.serializer.*
import io.ktor.client.request.*
import io.ktor.client.statement.*
import io.ktor.http.*
import io.ktor.util.cio.*
import io.ktor.utils.io.*
import jdr.exia.OLEBO_VERSION_CODE
import jdr.exia.model.dao.option.Settings
import jdr.exia.system.OLEBO_DIRECTORY
import jdr.exia.system.OS
import jdr.exia.view.tools.DefaultFunction
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.coroutineScope
import kotlinx.coroutines.launch
import java.io.File

private const val SERVER_URL = "http://localhost:8080/"

private val client = HttpClient {
    install(JsonFeature) {
        serializer = KotlinxSerializer()
    }
}

suspend fun checkForUpdate(): Release? {
    val response = try {
        client.get<HttpResponse>("${SERVER_URL}releases/last")
    } catch (e: Exception) {
        return null
    }

    if (response.status.isSuccess()) {
        return response.receive<Release>().takeIf { it.versionId > OLEBO_VERSION_CODE }
    }

    return null
}

suspend fun getInstallerExecutable(onUpdateProgress: (Long) -> Unit): Result<File> {
    val fileToWrite = File("$OLEBO_DIRECTORY${File.separator}olebo_updater.exe")

    val os = OS.current

    val response = try {
        client.get<HttpResponse>("${SERVER_URL}releases/last/download") {
            parameter("os", os.name)

            onDownload { bytesSentTotal, contentLength ->
                val percentage = (bytesSentTotal / contentLength) * 100
                onUpdateProgress(percentage)
            }
        }
    } catch (e: Exception) {
        return Result.failure(e)
    }

    if (response.status.isSuccess()) {
        response.content.copyAndClose(fileToWrite.writeChannel())
    } else return Result.failure(IllegalStateException("Response status : ${response.status.value}"))

    return Result.success(fileToWrite)
}

suspend fun downloadAndExit(
    onExitSuccess: DefaultFunction,
    onProgressUpdate: (Long) -> Unit = {},
    onDownloadSuccess: DefaultFunction = {},
    onDownloadFailure: (Throwable) -> Unit = {}
) = coroutineScope {
    this.launch(Dispatchers.IO) {
        getInstallerExecutable(onUpdateProgress = onProgressUpdate).onSuccess {
            onDownloadSuccess()

            Settings.wasJustUpdated = true

            // Run executable installer generated by Inno Setup
            Runtime.getRuntime().addShutdownHook(Thread {
                ProcessBuilder(it.absolutePath, "/SP-", "/silent", "/noicons").start()
            })

            onExitSuccess()
        }.onFailure(onDownloadFailure)
    }
}