package model.internationalisation

// Values whose keys are prefixed by STR are plain strings that should be formated.
// Those prefixed by ST are sentences already formated

// -- Strings

const val STR_VERSION = "version"
const val STR_FILES = "files"
const val STR_TAKE_SCREENSHOT = "take_screenshot"
const val STR_SAVE_AS = "save_as"
const val STR_EXPORT_DATA = "export_data"
const val STR_IMPORT_DATA = "import_data"
const val STR_AUTO_UPDATE = "auto_update"
const val STR_OLEBO_FILE = "olebo_file"
const val STR_ABOUT = "about"
const val STR_APP_VERSION = "app_version"
const val STR_DATABASE_VERSION = "dtb_version"
const val STR_ELEMENTS = "element"
const val STR_ADD_ACT = "add_act"
const val STR_OBJECT_LIST = "obj_list"
const val STR_OBJECTS = "obj"
const val STR_PC = "pc"
const val STR_NPC = "npc"
const val STR_NEW_ACT = "new_act"
const val STR_NAME = "name"
const val STR_CONFIRM = "confirm"
const val STR_NEW_SCENE = "new_scene"
const val STR_CHANGE_SCENE = "change_scene"
const val STR_NAME_OF_SCENE = "name_scene"
const val STR_IMPORT_IMG = "import_img"
const val STR_CANCEL = "cancel"
const val STR_SCENES = "scenes"
const val STR_NEW_ELEMENT = "new_element"
const val STR_CHANGE_ELEMENT = "change_element"
const val STR_NAME_OF_ELEMENT = "name_element"
const val STR_MAX_HEALTH = "hp_max"
const val STR_MAX_MANA = "mp_max"
const val STR_SEARCH = "search"
const val STR_BASE_ELEMENTS = "base"
const val STR_NO_ELEMENT = "no_element"
const val STR_DM_TITLE_FRAME = "master_frame_title"
const val STR_PLAYER_TITLE_FRAME = "player_frame_title"
const val STR_TOOLS = "tools"
const val STR_ENABLE_CURSOR = "enable_cursor"
const val STR_RESTORE = "restore"
const val STR_WINDOW = "window"
const val STR_CLOSE_ACT = "close_act"
const val STR_TOGGLE_PLAYER_FRAME = "toggle_player_frame"
const val STR_CHOOSE_SCENE = "choose_scene"
const val STR_IS_CURRENT_SCENE = "current_scene"
const val STR_TOKENS = "tokens"

// -- Sentences

const val ST_WARNING_CONFIG_RESET = "warn_conf_reset"
const val ST_CONFIGURATION_IMPORTED = "conf_imported"
const val ST_WARNING_PREVIOUS_VERSION_FILE = "warn_prev_file"
const val ST_WARNING_MISSING_CONF_FILES = "missing_conf_files"
const val ST_UNKNOWN_ERROR = "err_unknown"
const val ST_FILE_MAY_BE_CORRUPTED = "file_corrupted"
const val ST_ACT_ALREADY_EXISTS = "act_already_exists"
const val ST_SCENE_ALREADY_EXISTS = "scene_already_exists"
const val ST_FILE_ALREADY_EXISTS = "file_already_exists"
const val ST_ELEMENT_ALREADY_EXISTS = "element_already_exists"