name: Inno test

on:
  push:
    branches: [ Github-action ]
  pull_request:
    branches: [ Github-action ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Chocolatey
      run: Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
    - name: Install Inno Setup
      run: 'choco install innosetup'
    - name: Test
      run: 'iscc'
