name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - develop
      - master
      - feature/Olebo-2

jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Create coverage data directory
        run: mkdir -p .qodana/code-coverage
      - name: Generate coverage report
        run: ./gradlew koverBinaryReport
      - name: Move and rename coverage report
        run: cp build/reports/kover/report.bin .qodana/code-coverage/report.ic
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2023.3
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
        with:
          args: -b /data/base/qodana.sarif.json